airport_city_dict = {
    'DFW': 'Dallas/Fort Worth',
    'DTW': 'Detroit',
    'SEA': 'Seattle',
    'JFK': 'New York',
    'SJC': 'San Jose',
    'ORD': 'Chicago',
    'PHX': 'Phoenix',
    'STL': 'St. Louis',
    'LAX': 'Los Angeles',
    'MCO': 'Orlando',
    'DEN': 'Denver',
    'MIA': 'Miami',
    'KOA': 'Kona',
    'IAH': 'Houston',
    'AUS': 'Austin',
    'LAS': 'Las Vegas',
    'SLC': 'Salt Lake City',
    'TUS': 'Tucson',
    'STT': 'Saint Thomas',
    'BOS': 'Boston',
    'FLL': 'Fort Lauderdale',
    'SFO': 'San Francisco',
    'OGG': 'Kahului',
    'TPA': 'Tampa',
    'SNA': 'Santa Ana',
    'OKC': 'Oklahoma City',
    'HNL': 'Honolulu',
    'PHL': 'Philadelphia',
    'LGA': 'New York',
    'RDU': 'Raleigh/Durham',
    'DCA': 'Washington, D.C.',
    'RIC': 'Richmond',
    'ATL': 'Atlanta',
    'LBB': 'Lubbock',
    'CLT': 'Charlotte',
    'ELP': 'El Paso',
    'SAN': 'San Diego',
    'BNA': 'Nashville',
    'JAC': 'Jackson Hole',
    'SMF': 'Sacramento',
    'EWR': 'Newark',
    'IAD': 'Washington, D.C.',
    'LIH': 'Lihue',
    'SJU': 'San Juan',
    'ABQ': 'Albuquerque',
    'ORF': 'Norfolk',
    'JAX': 'Jacksonville',
    'MSY': 'New Orleans',
    'SAT': 'San Antonio',
    'MCI': 'Kansas City',
    'GUC': 'Gunnison',
    'IND': 'Indianapolis',
    'PDX': 'Portland',
    'BWI': 'Baltimore',
    'MSP': 'Minneapolis/St. Paul',
    'MKE': 'Milwaukee',
    'TUL': 'Tulsa',
    'ONT': 'Ontario',
    'RSW': 'Fort Myers',
    'RNO': 'Reno',
    'DSM': 'Des Moines',
    'MFE': 'McAllen',
    'PSP': 'Palm Springs',
    'OMA': 'Omaha',
    'EGE': 'Eagle',
    'PBI': 'West Palm Beach',
    'SDF': 'Louisville',
    'PIT': 'Pittsburgh',
    'FAT': 'Fresno',
    'DAY': 'Dayton',
    'STX': 'Saint Croix',
    'COS': 'Colorado Springs',
    'CMH': 'Columbus',
    'MTJ': 'Montrose',
    'HDN': 'Hayden',
    'BDL': 'Hartford',
    'MEM': 'Memphis',
    'CLE': 'Cleveland',
    'HOU': 'Houston',
    'BOI': 'Boise',
    'OAK': 'Oakland',
    'GEG': 'Spokane',
    'ANC': 'Anchorage',
    'BUF': 'Buffalo',
    'SYR': 'Syracuse',
    'ALB': 'Albany',
    'PVD': 'Providence',
    'ROC': 'Rochester',
    'ILM': 'Wilmington',
    'ICT': 'Wichita',
    'PWM': 'Portland',
    'GSO': 'Greensboro',
    'CHS': 'Charleston',
    'MDT': 'Harrisburg',
    'BHM': 'Birmingham',
    'ADQ': 'Kodiak',
    'BET': 'Bethel',
    'BRW': 'Barrow',
    'SCC': 'Deadhorse',
    'FAI': 'Fairbanks',
    'JNU': 'Juneau',
    'KTN': 'Ketchikan',
    'YAK': 'Yakutat',
    'CDV': 'Cordova',
    'SIT': 'Sitka',
    'PSG': 'Petersburg',
    'WRG': 'Wrangell',
    'OME': 'Nome',
    'OTZ': 'Kotzebue',
    'BUR': 'Burbank',
    'BLI': 'Bellingham',
    'ADK': 'Adak',
    'SWF': 'New Windsor',
    'LGB': 'Long Beach',
    'PSE': 'Ponce',
    'BQN': 'Aguadilla',
    'HPN': 'White Plains',
    'SAV': 'Savannah',
    'SRQ': 'Sarasota',
    'BTV': 'Burlington',
    'ORH': 'Worcester',
    'DAB': 'Daytona Beach',
    'CVG': 'Cincinnati',
    'BIS': 'Bismarck',
    'AVL': 'Asheville',
    'GRR': 'Grand Rapids',
    'FNT': 'Flint',
    'MYR': 'Myrtle Beach',
    'JAN': 'Jackson',
    'BIL': 'Billings',
    'FAR': 'Fargo',
    'PNS': 'Pensacola',
    'AGS': 'Augusta',
    'GSP': 'Greenville',
    'LEX': 'Lexington',
    'DAL': 'Dallas',
    'ATW': 'Appleton',
    'GPT': 'Gulfport',
    'MLB': 'Melbourne',
    'BZN': 'Bozeman',
    'CAK': 'Akron',
    'CHO': 'Charlottesville',
    'MSN': 'Madison',
    'EYW': 'Key West',
    'TRI': 'Tri-Cities',
    'LFT': 'Lafayette',
    'ROA': 'Roanoke',
    'ECP': 'Panama City',
    'VPS': 'Valparaiso',
    'XNA': 'Bentonville',
    'EVV': 'Evansville',
    'AVP': 'Wilkes-Barre',
    'MDW': 'Chicago',
    'HSV': 'Huntsville',
    'FAY': 'Fayetteville',
    'LIT': 'Little Rock',
    'TYS': 'Knoxville',
    'TLH': 'Tallahassee',
    'MSO': 'Missoula',
    'CHA': 'Chattanooga',
    'TTN': 'Trenton',
    'UST': 'St. Augustine',
    'MOB': 'Mobile',
    'PHF': 'Newport News',
    'CAE': 'Columbia',
    'FSD': 'Sioux Falls',
    'ITO': 'Hilo',
    'LBE': 'Latrobe',
    'ABE': 'Allentown',
    'BMI': 'Bloomington',
    'CRW': 'Charleston',
    'ACY': 'Atlantic City',
    'PPG': 'Pago Pago',
    'IAG': 'Niagara Falls',
    'ACT': 'Waco',
    'MLU': 'Monroe',
    'GRK': 'Killeen',
    'SHV': 'Shreveport',
    'FSM': 'Fort Smith',
    'MAF': 'Midland',
    'SAF': 'Santa Fe',
    'JLN': 'Joplin',
    'LRD': 'Laredo',
    'BRO': 'Brownsville',
    'TYR': 'Tyler',
    'GJT': 'Grand Junction',
    'YUM': 'Yuma',
    'DLH': 'Duluth',
    'GRB': 'Green Bay',
    'LAN': 'Lansing',
    'SBA': 'Santa Barbara',
    'ASE': 'Aspen',
    'DRO': 'Durango',
    'IDA': 'Idaho Falls',
    'RAP': 'Rapid City',
    'FCA': 'Kalispell',
    'LNK': 'Lincoln',
    'AMA': 'Amarillo',
    'BFL': 'Bakersfield',
    'MLI': 'Moline',
    'LSE': 'La Crosse',
    'SBN': 'South Bend',
    'PSC': 'Pasco',
    'MOT': 'Minot',
    'FLG': 'Flagstaff',
    'ISN': 'Williston',
    'GFK': 'Grand Forks',
    'GTF': 'Great Falls',
    'FWA': 'Fort Wayne',
    'MRY': 'Monterey',
    'MBS': 'Saginaw',
    'PIA': 'Peoria',
    'SUN': 'Sun Valley',
    'TWF': 'Twin Falls',
    'SGF': 'Springfield',
    'CPR': 'Casper',
    'BTR': 'Baton Rouge',
    'PBG': 'Plattsburgh',
    'CRP': 'Corpus Christi',
    'CID': 'Cedar Rapids',
    'SBP': 'San Luis Obispo',
    'RKS': 'Rock Springs',
    'CMX': 'Hancock',
    'MMH': 'Mammoth Lakes',
    'PLN': 'Pellston',
    'EKO': 'Elko',
    'GCC': 'Gillette',
    'AZO': 'Kalamazoo',
    'MFR': 'Medford',
    'SMX': 'Santa Maria',
    'EUG': 'Eugene',
    'RST': 'Rochester',
    'TVC': 'Traverse City',
    'SPI': 'Springfield',
    'SGU': 'St. George',
    'HLN': 'Helena',
    'RDM': 'Redmond',
    'ACV': 'Arcata',
    'EAU': 'Eau Claire',
    'DVL': 'Devils Lake',
    'JMS': 'Jamestown',
    'MKG': 'Muskegon',
    'HYS': 'Hays',
    'PAH': 'Paducah',
    'COD': 'Cody',
    'ABR': 'Aberdeen',
    'ITH': 'Ithaca',
    'APN': 'Alpena',
    'ESC': 'Escanaba',
    'BJI': 'Bemidji',
    'MQT': 'Marquette',
    'CIU': 'Sault Ste. Marie',
    'BGM': 'Binghamton',
    'RHI': 'Rhinelander',
    'LWS': 'Lewiston',
    'IMT': 'Iron Mountain',
    'BRD': 'Brainerd',
    'INL': 'International Falls',
    'PIH': 'Pocatello',
    'GUM': 'Guam',
    'HIB': 'Hibbing',
    'BTM': 'Butte',
    'CDC': 'Cedar City',
    'OTH': 'North Bend',
    'RDD': 'Redding',
    'MHT': 'Manchester',
    'GNV': 'Gainesville',
    'MEI': 'Meridian',
    'PIB': 'Hattiesburg',
    'BPT': 'Beaumont',
    'LAW': 'Lawton',
    'AEX': 'Alexandria',
    'TXK': 'Texarkana',
    'ROW': 'Roswell',
    'ERI': 'Erie',
    'CLL': 'College Station',
    'HOB': 'Hobbs',
    'LCH': 'Lake Charles',
    'HRL': 'Harlingen',
    'CWA': 'Wausau',
    'OAJ': 'Jacksonville',
    'ELM': 'Elmira',
    'VLD': 'Valdosta',
    'MGM': 'Montgomery',
    'BGR': 'Bangor',
    'GTR': 'Columbus',
    'CSG': 'Columbus',
    'BQK': 'Brunswick',
    'DHN': 'Dothan',
    'EWN': 'New Bern',
    'ABY': 'Albany',
    'SCE': 'State College',
    'ISP': 'Islip',
    'LAR': 'Laramie',
    'SPS': 'Wichita Falls',
    'SJT': 'San Angelo',
    'GGG': 'Longview',
    'WYS': 'West Yellowstone',
    'ACK': 'Nantucket',
    'MVY': 'Martha\'s Vineyard',
    'HYA': 'Hyannis',
    'GST': 'Gustavus',
    'AKN': 'King Salmon',
    'DLG': 'Dillingham',
    'GCK': 'Garden City',
    'MHK': 'Manhattan',
    'ABI': 'Abilene',
    'GRI': 'Grand Island',
    'EFD': 'Houston',
    'PGD': 'Punta Gorda',
    'SPN': 'Saipan'
}
airport_options = [(code, f"{code} - {city}") for code, city in airport_city_dict.items()]
compagnies_aeriennes = sorted(['AA', 'AS', 'B6', 'DL', 'F9', 'HA', 'NK', 'EV', 'OO', 'UA', 'VX', 'WN'])
carriersfull=['American Airlines', 'Alaska Airlines', 'JetBlue Airways', 'Delta Airlines','Frontier Airlines Inc.','Hawaiian Airlines Inc.','Spirit Airlines','ExpressJet Airlines','Skywest Airlines','United Airlines','Virgin America','Southwest Airlines']
compagnies_aeriennes_dict = {
    'American Airlines': 'AA',
    'Alaska Airlines': 'AS',
    'JetBlue Airways': 'B6',
    'Delta Airlines': 'DL',
    'Frontier Airlines Inc.': 'F9',
    'Hawaiian Airlines Inc.': 'HA',
    'Spirit Airlines': 'NK',
    'ExpressJet Airlines': 'EV',
    'Skywest Airlines': 'OO',
    'United Airlines': 'UA',
    'Virgin America': 'VX',
    'Southwest Airlines': 'WN'
}
aeroports=sorted(['DFW', 'DTW', 'SEA', 'JFK', 'SJC', 'ORD', 'PHX', 'STL', 'LAX',
       'MCO', 'DEN', 'MIA', 'KOA', 'IAH', 'AUS', 'LAS', 'SLC', 'TUS',
       'STT', 'BOS', 'FLL', 'SFO', 'OGG', 'TPA', 'SNA', 'OKC', 'HNL',
       'PHL', 'LGA', 'RDU', 'DCA', 'RIC', 'ATL', 'LBB', 'CLT', 'ELP',
       'SAN', 'BNA', 'JAC', 'SMF', 'EWR', 'IAD', 'LIH', 'SJU', 'ABQ',
       'ORF', 'JAX', 'MSY', 'SAT', 'MCI', 'GUC', 'IND', 'PDX', 'BWI',
       'MSP', 'MKE', 'TUL', 'ONT', 'RSW', 'RNO', 'DSM', 'MFE', 'PSP',
       'OMA', 'EGE', 'PBI', 'SDF', 'PIT', 'FAT', 'DAY', 'STX', 'COS',
       'CMH', 'MTJ', 'HDN', 'BDL', 'MEM', 'CLE', 'HOU', 'BOI', 'OAK',
       'GEG', 'ANC', 'BUF', 'SYR', 'ALB', 'PVD', 'ROC', 'ILM', 'ICT',
       'PWM', 'GSO', 'CHS', 'MDT', 'BHM', 'ADQ', 'BET', 'BRW', 'SCC',
       'FAI', 'JNU', 'KTN', 'YAK', 'CDV', 'SIT', 'PSG', 'WRG', 'OME',
       'OTZ', 'BUR', 'BLI', 'ADK', 'SWF', 'LGB', 'PSE', 'BQN', 'HPN',
       'SAV', 'SRQ', 'BTV', 'ORH', 'DAB', 'CVG', 'BIS', 'AVL', 'GRR',
       'FNT', 'MYR', 'JAN', 'BIL', 'FAR', 'PNS', 'AGS', 'GSP', 'LEX',
       'DAL', 'ATW', 'GPT', 'MLB', 'BZN', 'CAK', 'CHO', 'MSN', 'EYW',
       'TRI', 'LFT', 'ROA', 'ECP', 'VPS', 'XNA', 'EVV', 'AVP', 'MDW',
       'HSV', 'FAY', 'LIT', 'TYS', 'TLH', 'MSO', 'CHA', 'TTN', 'UST',
       'MOB', 'PHF', 'CAE', 'FSD', 'ITO', 'LBE', 'ABE', 'BMI', 'CRW',
       'ACY', 'PPG', 'IAG', 'ACT', 'MLU', 'GRK', 'SHV', 'FSM', 'MAF',
       'SAF', 'JLN', 'LRD', 'BRO', 'TYR', 'GJT', 'YUM', 'DLH', 'GRB',
       'LAN', 'SBA', 'ASE', 'DRO', 'IDA', 'RAP', 'FCA', 'LNK', 'AMA',
       'BFL', 'MLI', 'LSE', 'SBN', 'PSC', 'MOT', 'FLG', 'ISN', 'GFK',
       'GTF', 'FWA', 'MRY', 'MBS', 'PIA', 'SUN', 'TWF', 'SGF', 'CPR',
       'BTR', 'PBG', 'CRP', 'CID', 'SBP', 'RKS', 'CMX', 'MMH', 'PLN',
       'EKO', 'GCC', 'AZO', 'MFR', 'SMX', 'EUG', 'RST', 'TVC', 'SPI',
       'SGU', 'HLN', 'RDM', 'ACV', 'EAU', 'DVL', 'JMS', 'MKG', 'HYS',
       'PAH', 'COD', 'ABR', 'ITH', 'APN', 'ESC', 'BJI', 'MQT', 'CIU',
       'BGM', 'RHI', 'LWS', 'IMT', 'BRD', 'INL', 'PIH', 'GUM', 'HIB',
       'BTM', 'CDC', 'OTH', 'RDD', 'MHT', 'GNV', 'MEI', 'PIB', 'BPT',
       'LAW', 'AEX', 'TXK', 'ROW', 'ERI', 'CLL', 'HOB', 'LCH', 'HRL',
       'CWA', 'OAJ', 'ELM', 'VLD', 'MGM', 'BGR', 'GTR', 'CSG', 'BQK',
       'DHN', 'EWN', 'ABY', 'SCE', 'ISP', 'LAR', 'SPS', 'SJT', 'GGG',
       'WYS', 'ACK', 'MVY', 'HYA', 'GST', 'AKN', 'DLG', 'GCK', 'MHK',
       'ABI', 'GRI', 'EFD', 'PGD', 'SPN'])

def get_city_name(airport_code):
    return airport_city_dict.get(airport_code, "Code aéroport inconnu")
